version: '3.9'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-db:/var/lib/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-db: